---
title: "Portrait énergétique et carbone européen"
---

Cette étude présente les données de diverses sources dont celles de [Gapminder](https://www.gapminder.org/data/documentation/gd004/) et de [Our World in Data](https://ourworldindata.org/) et adopte une perspective européenne.

Il y a aussi un fort appuie sur les données de [Eurostat](https://ec.europa.eu/eurostat/) qui permettent entre autre de créer des cartes européennes, des tables et d'avoir les coordonnées des pays européens.


Premièrement on observe les prédictions de [Gapminder](https://www.gapminder.org/data/documentation/gd004/) quant aux évolutions de l'espérance de vie des ciotyens européens qui serait en hausse jusqu'en 2100. Cependant, des écarts dans l'espérance de vie peuvent être perçus entre les pays de l'Union européenne. L'Union europééenne n'est pas unilatérales dans ses perspectives d'espérance de vie et ne propose pas à tout ces citoyens les mêmes qualités de vie.


```{r, message=FALSE, warning=FALSE  }
library(ggplot2)
library(tidyverse)
library(rgdal)
library(rmapshaper)
library(sp)
library(sf)
library(broom)
library(maps)
library(rworldmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(gridBase)
library(lessR)
library(ggrepel)
europe <- readOGR(dsn = "NUTS_RG_20M_2021_3035.shp",
                  layer = "NUTS_RG_20M_2021_3035")
european_table <- tidy(x = europe, region = "CNTR_CODE")
colnames(european_table) <- c("long","lat","order","hole","piece","group","pays")

europe_carte <- ggplot(data = european_table, aes(x = long, y = lat, group = group, fill = "#FAA219"))+ 
  geom_polygon(fill= "#FAA219")+
  ylim(1000000, 5500000)+
  xlim(2000000,7500000)+
  theme_void()+
  theme(plot.background=element_rect(fill = "#012b36"))
europe_carte
```

<aside>pays européens</aside>

Les données de [Our World in Data](https://ourworldindata.org/) nous démontrent tout de même une amélioration des empreintes carbones liées à la consommation et prouction énergétiques européennes depuis les années 2000. 
